### ISSUE TITLE
Can not build TS_HelloWorld unless IVCT_Framework is already built.

### ISSUE THREAD

**Issue by PHameete** [MSG134/TS_HelloWorld#32]
Currently, the build for TS_HelloWorld expects that the user has already built the IVCT_Framework locally (IE these projects are present in the local maven repository). In particular because it needs the IEEE1516e dummy HLA runtime.

However. If we wish to build the TS_HelloWorld automatically, the IVCT_Framework projects will NOT be present in the local repository. 

Discuss: how can we make the required projects from IVCT_Framework available when checking out TS_HelloWorld separately, and building it on a 'fresh' machine.

**Comment by ducana** [comment]
The necessary libraries have been placed in the sonatype maven repository under io.github.msg134. This now means that travis can run the repository tests and test case writers can write and compile the test cases without requiring the IVCT_Framework.
