### ISSUE TITLE
Allow request paraeters to be provided on command line or as env setting

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/TS_HelloWorld#37]
Currently only the CRC host can be provided on the HelloWorld command line.

To enable automation (and containerization) it should be possible to provide all parameters on the commandline or as an env setting: country name, starting population, and number of cycles.

**Comment by ducana** [comment]
Have changed HelloWorld to also use command line arguments:
eg. HelloWorld.bat 10.1.4.29 A 10 3000
which means using the gradlew generated bat file with the arguments: CRChost countryName startingPopulation numberOfCycles (Defaults: countryName A, startingPopulation 100, numberOfCycles 1000)
The previous usage with no command line arguments stays the same.
